BusReservation/Controllers/RoleController.cs
using BusReservation.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BusReservation.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();

        // GET: Role
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

BusReservation/Views/Role/AssignRoleToUser.cshtml
@{
    ViewBag.Title = "AssignRoleToUser";
}

<h2>Assign Role To User</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.Label("Select your user type", new { @class = "col-md-2 control-label" });
        <div class="col-md-10">
            @Html.DropDownList("UserName"); 
        </div>
    </div>
    <input type="submit" value="Create Role"/>
}

BusReservation/Views/Role/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<style>
    #tbrole, .c {
        border: double;
    }
</style>

@using (Html.BeginForm())
{
    <table class="table table-bordered table-hover">
        <tr>
            <td class="c"> Enter Role Name To Be Created</td>
            <td class="c">
                @Html.EditorFor(m => m.Name);
            </td>
        </tr>
    </table>
    <input class="btn btn-primary" type="submit" value="Create Role" />
}

BusReservation/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<h2>Available Roles For Application</h2>

<section class="col-md-6">
        <table class="table-bordered">
            @Html.ActionLink("Create Role", "Create", "Role")
        </table>
</section>
<section class="col-md-6">
    <table class="table-bordered">
        @Html.ActionLink("Assign Role To User", "RegisterRole", "Account")
    </table>
</section>

<br />

<table class="table table-bordered table-hover">
    <tr>
        <th class="c">
            Role Name
        </th>
        @foreach(var item in Model)
        {
            <tr>
                <td>
                    @item.Name
                </td>
            </tr>
        }
    </tr>
</table>