BusReservation/Models/Destination.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BusReservation.Models
{
    public class Destination
    {
        public int DestinationId { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        [DisplayName("Price (One Way)")]
        public int PriceOneWay { get; set; }
        [DisplayName("Price (Two Way)")]
        public int PriceTwoWay { get; set; }
        [DisplayName("Price (Student)")]
        public int PriceStudent { get; set; }
        public int BusId { get; set; }
        
        public Bus Bus { get; set; }
        
        public virtual List<Ticket> Tickets { get; set; }
        

        public Destination()
        {
            Tickets = new List<Ticket>();
        }

        public Destination(int destinationId, string from, string to, int priceOneWay, int priceTwoWay, int priceStudent, Bus bus, List<Ticket> tickets)
        {
            DestinationId = destinationId;
            From = from;
            To = to;
            PriceOneWay = priceOneWay;
            PriceTwoWay = priceTwoWay;
            PriceStudent = priceStudent;
            Tickets = tickets;
            this.Bus = bus;
            string FullNameDestination = From + "-" + To;
            
        }

        
    }
}

BusReservation/Controllers/DestinationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using BusReservation.Models;

namespace BusReservation.Controllers
{
    public class DestinationsController : Controller
    {
        private BusReservationContext db = new BusReservationContext();

        // GET: Destinations
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Destinations.ToList());
        }

        // GET: Destinations/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            Bus bus = db.Buses.Find(destination.BusId);
            destination.Bus = bus;
            destination.Tickets = db.Tickets.Where(ticket => ticket.DestinationId == destination.DestinationId).ToList<Ticket>();
            if (destination == null)
            {
                return HttpNotFound();
            }
            
            ViewModel des = new ViewModel();
            des.Destinations = destination;
            des.Tickets = destination.Tickets;
            List<SelectListItem> list = new List<SelectListItem>
            {
            new SelectListItem { Text = "--- Select ---", Value = 0.ToString() },
            new SelectListItem { Text = "One Way Price ("+ destination.PriceOneWay.ToString()+")" , Value = destination.PriceOneWay.ToString() },
            new SelectListItem { Text = "Two Way Price ("+ destination.PriceTwoWay.ToString()+")", Value = destination.PriceTwoWay.ToString()},
            new SelectListItem { Text = "Student Price ("+ destination.PriceStudent.ToString()+")", Value = destination.PriceStudent.ToString() },
            };
            ViewBag.ceni = list;
            ViewBag.destination = destination;
            return View(des);
        }

        // GET: Destinations/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (var bus in db.Buses.ToList<Bus>())
            {
                list.Add(new SelectListItem() { Value = bus.BusId.ToString(), Text = bus.Name });
            }
            ViewBag.Busovi = list;
            //ViewBag.Avtobusi = db.Buses.ToList<Bus>();
            return View();
        }

        // POST: Destinations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DestinationId,From,To,PriceOneWay,PriceTwoWay,PriceStudent,BusId")] Destination destination)
        {
            if (ModelState.IsValid)
            {
                db.Destinations.Add(destination);
                //list<bus> buses = db.buses.tolist<bus>();
                //bus bus = buses.find(x => x.busid == destination.busid);
                //for(int i = 0; i < bus.numberofseats; i++)
                //{
                //    ticket ticket = new ticket();
                //    db.tickets.add(ticket);
                //}
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(destination);
        }

        // GET: Destinations/Edit/5
        [Authorize(Roles ="Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            if (destination == null)
            {
                return HttpNotFound();
            }
            return View(destination);
        }

        // POST: Destinations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DestinationId,From,To,PriceOneWay,PriceTwoWay,PriceStudent")] Destination destination)
        {
            if (ModelState.IsValid)
            {
                db.Entry(destination).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(destination);
        }

        // GET: Destinations/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            if (destination == null)
            {
                return HttpNotFound();
            }
            return View(destination);
        }

        // POST: Destinations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Destination destination = db.Destinations.Find(id);
            db.Destinations.Remove(destination);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BusReservation/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using BusReservation.Models;
using Microsoft.AspNet.Identity;

namespace BusReservation.Controllers
{
    public class TicketsController : Controller
    {
        private BusReservationContext db = new BusReservationContext();
        public List<int> list = new List<int>();

        // GET: Tickets
        [Authorize]
        public ActionResult Index()
        {
            var userID = User.Identity.GetUserId();
            var list = db.Tickets.Where(x => x.UserId == userID).ToList();
            return View(list);
        }

        // GET: Tickets/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Tickets/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Avtobusi = db.Buses.ToList<Bus>();
            ViewBag.Destinacii = db.Destinations.ToList<Destination>();
            
            return View();
        }


        [HttpPost]
        [Authorize]
        public ActionResult Test(string ReturnedObject)
        {
            Ticket ticket = new Ticket();
            if (ModelState.IsValid)
            {
                if (ReturnedObject != null)
                {
                    var JSONObj = new JavaScriptSerializer().Deserialize<Dictionary<string, string>>(ReturnedObject);
                    ticket.Type = int.Parse(JSONObj["Type"]);
                    ticket.Price = int.Parse(JSONObj["Price"]);
                    //ticket.Date = new DateTime(long.Parse(JSONObj["Date"]));
                    ticket.Peron = int.Parse(JSONObj["Peron"]);
                    ticket.DestinationId = int.Parse(JSONObj["DestinationId"]);
                    ticket.UserId = User.Identity.GetUserId();
                    int id = int.Parse(JSONObj["BusId"]);
                    Bus bus = (Bus)db.Buses.Find(id);
                    ticket.Destination = (Destination) db.Destinations.Find(ticket.DestinationId);
                    ticket.Destination.Bus = bus;
                    string[] arr = JSONObj["seatNo"].Split(',');
                    int[] seatsNo = Array.ConvertAll(arr, s => int.Parse(s));
                    if(User.Identity.IsAuthenticated == true)
                    {
                        for (int i = 0; i < seatsNo.Length; i++)
                        {
                            ticket.SeatNumber = seatsNo[i];
                            db.Tickets.Add(ticket);
                            db.SaveChanges();
                        }
                        ticket.Price = ticket.Price * seatsNo.Length;
                    }
                    else
                    {
                        return RedirectToAction("Login", "Account");
                    }

                    
                    //ticket.bus = JSONObj["BusId"];
                }
                
                
            }

            return View(ticket);
         
        }

        //POST: Tickets/Create
        //To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(string TicketsNo, [Bind(Include = "TicketId,Type,Price,Date,SeatNumber,Peron,DestinationId")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                if (User.Identity.IsAuthenticated)
                {
                    ticket.UserId = User.Identity.GetUserId();
                    string[] arr = TicketsNo.Split(',');
                    db.Tickets.Add(ticket);
                    db.SaveChanges();
                    //Destination destination = db.Destinations.Find(ticket.DestinationId);
                    
                    return RedirectToAction("Index");
                }   
            }

            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "TicketId,Type,Price,Date,SeatNumber,Peron")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Ticket ticket = db.Tickets.Find(id);
            db.Tickets.Remove(ticket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BusReservation/Views/Destinations/Create.cshtml
@model BusReservation.Models.Destination

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Destination</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.To, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.To, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PriceOneWay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PriceOneWay, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PriceOneWay, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PriceTwoWay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PriceTwoWay, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PriceTwoWay, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PriceStudent, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PriceStudent, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PriceStudent, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BusId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("BusId", (IEnumerable<SelectListItem>)ViewBag.Busovi, new { @class = "dropdown" })
            @Html.ValidationMessageFor(model => model.Bus, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BusReservation/Views/Destinations/Delete.cshtml
@model BusReservation.Models.Destination

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Destination</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.To)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.To)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceOneWay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceOneWay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceTwoWay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceTwoWay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceStudent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceStudent)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BusReservation/Views/Destinations/Details.cshtml
@model BusReservation.Controllers.ViewModel

@{
    ViewBag.Title = "Details";
}

<style>

    .whatever {
        background-color: green;
        display: inline-block;
        width: 15px;
        height: 15px;
    }

    #checkboxes input[type=checkbox] {
        display: none;
    }

        #checkboxes input[type=checkbox]:checked + .whatever {
            background-color: red;
        }
</style>

<h2>Destination: @Model.Destinations.From - @Model.Destinations.To</h2>
<h4>Destination</h4>
<hr />



@using (Html.BeginForm("Test", "Tickets", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="row">
            <div class="col-md-6">
                <div>

                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Destinations.From)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Destinations.From)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Destinations.To)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Destinations.To)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Destinations.PriceOneWay)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Destinations.PriceOneWay)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Destinations.PriceTwoWay)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Destinations.PriceTwoWay)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Destinations.PriceStudent)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Destinations.PriceTwoWay)
                        </dd>

                    </dl>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <input data-val="true" data-val-number="The field DestinationId must be a number." data-val-required="The DestinationId field is required."
                       id="DestinationId" name="DestinationId" type="hidden" value="@Model.Destinations.DestinationId" />

                @Html.HiddenFor(model => model.Destinations.BusId)
                @{
                    Random r = new Random();

                }
                <input data-val="true" data-val-number="The field Type must be a number." data-val-required="The Type field is required." id="Type" name="Type" type="hidden" value="@r.Next(1,3)" />



                <div class="form-group">
                    @Html.LabelFor(model => model.Tickets[0].Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select name="Price" class="dropdownlist" id="Price">
                            @foreach (SelectListItem item in ViewBag.ceni)
                            {
                                <option value="@(item.Value)" selected="selected">@item.Text</option>
                            }
                        </select>
                        @Html.ValidationMessageFor(model => model.Tickets[0].Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Tickets[0].Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                        <input type="text" class="form-control Date" id="Date" name="Date" value="">
                        @Html.ValidationMessageFor(model => model.Tickets[0].Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*
                    <div class="form-group">
                        @Html.LabelFor(model => model.Tickets.SeatNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input class="form-control text-box single-line" data-val="true" data-val-number="The field Seat Number must be a number." data-val-required="The Seat Number field is required." id="SeatNumber" name="SeatNumber" type="number" value="" />
                            @Html.ValidationMessageFor(model => model.Tickets.SeatNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>
                *@
                <input id="Peron" name="Peron" type="hidden" value="@r.Next(3,10)">

                @*
                    <div class="form-group">
                        @Html.LabelFor(model => model.Buses, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("Buses", new SelectList(ViewBag.Avtobusi, "BusId", "Name"), new { @class = "dropdown" })
                            @Html.ValidationMessageFor(model => model.Peron, "", new { @class = "text-danger" })
                        </div>
                    </div>
                *@
            </div>
            <div class="col-md-6">
                <div id="checkboxes" class=" col-md-3 " style="">
                    @{
                        bool flag = false;
                    }
                    @for (int i = 1; i <= Model.Destinations.Bus.NumberOfSeats; i++)
                    {
                        for (int j = 0; j < Model.Tickets.Count; j++)
                        {
                            if (i == Model.Tickets[j].SeatNumber)
                            {
                                flag = true;
                                <input type="checkbox" name="SeatNumber" value="@i" id="@i" disabled />
                                <label class="whatever" style="background-color:darkgrey" for="@i"></label>
                            }
                        }
                        if (flag)
                        {
                            flag = false;
                            continue;
                        }
                        <input type="checkbox" name="SeatNumber" value="@i" id="@i" />
                        <label class="whatever" for="@i"></label>
                    }
                </div>`
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Buy Ticket" onclick="SaveList()" class="btn btn-default" />

                @*<input type="submit" value="Buy" onclick="SaveList()" class="btn btn-primary" />*@
            </div>
        </div>
    </div>
    <script>
        var SaveList = function () {
            var array = [];
            var idString = '';
            $("#checkboxes input[type=checkbox]").each(function (index, val) {
                
                var checkId = $(val).attr("id");
                var value = $(val).val();
                var isChecked = $("#" + checkId).is(":checked", true);
                if (isChecked) {
                    array.push(value.toString())
                }
            })

            if (array.length != 0) {
                var nizaSedista = [];
                var returnObject = {};
                returnObject.Type = document.getElementById("Type").value;
                returnObject.Price = document.getElementById("Price").value;
                returnObject.Date = document.getElementById("Date").value;
                returnObject.Peron = document.getElementById("Peron").value;
                returnObject.DestinationId = document.getElementById("DestinationId").value;
                returnObject.BusId = document.getElementById("Destinations_BusId").value;
                returnObject.seatNo = array.toString();
             
                var url = "/Tickets/Test";

                $.ajax({
                    url: url,
                    type: 'POST',
                    data: { ReturnedObject: JSON.stringify(returnObject) },
                    async: false,
                    cache: false,
                    timeout: 2000,
                    success: function (msg) {
                        
                    }
                });
            }   
        }
    </script>
}

    <p>
        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.Destinations.DestinationId })
        }
        |
        @Html.ActionLink("Back to List", "Index")
    </p>

BusReservation/Views/Destinations/Edit.cshtml
@model BusReservation.Models.Destination

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Destination</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DestinationId)

        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.To, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.To, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceOneWay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceOneWay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceOneWay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceTwoWay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceTwoWay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceTwoWay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceStudent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceStudent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceStudent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BusReservation/Views/Destinations/Index.cshtml
@model IEnumerable<BusReservation.Models.Destination>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @if (ViewContext.HttpContext.User.IsInRole("Admin"))
    {
        @Html.ActionLink("Create New", "Create")
    }
    </p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.From)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.To)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PriceOneWay)
        </th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr>
       <td>
            @Html.DisplayFor(modelItem => item.From)
        </td>
       <td>
           @if (ViewContext.HttpContext.User.IsInRole("Your role"))
           {
               // Do something here
           }
           @Html.DisplayFor(modelItem => item.To)
       </td>
        <td>
            @Html.DisplayFor(modelItem => item.PriceOneWay)
        </td>
        <td>
            @if (ViewContext.HttpContext.User.IsInRole("Admin"))
            {
                @Html.ActionLink("Edit", "Edit", new { id = item.DestinationId })
                <span>|</span>
            }
            
            @if (ViewContext.HttpContext.User.IsInRole("Admin"))
            {
                @Html.ActionLink("Delete", "Delete", new { id = item.DestinationId })
                <span>|</span>
            }
            
            @Html.ActionLink("Details", "Details", new { id = item.DestinationId })


        </td>
    </tr>
}
    

</table>
<style>

</style>
<script>
    
</script>