BusReservation/Controllers/BusesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusReservation.Models;

namespace BusReservation.Controllers
{
    public class BusesController : Controller
    {
        private BusReservationContext db = new BusReservationContext();

        // GET: Buses
        public ActionResult Index()
        {
            return View(db.Buses.ToList());
        }

        // GET: Buses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // GET: Buses/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Buses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BusId,Name,NumberOfSeats")] Bus bus)
        {
            if (ModelState.IsValid)
            {
                db.Buses.Add(bus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bus);
        }

        // GET: Buses/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // POST: Buses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BusId,Name,NumberOfSeats")] Bus bus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bus);
        }

        // GET: Buses/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // POST: Buses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bus bus = db.Buses.Find(id);
            db.Buses.Remove(bus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BusReservation/Controllers/DestinationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using BusReservation.Models;

namespace BusReservation.Controllers
{
    public class DestinationsController : Controller
    {
        private BusReservationContext db = new BusReservationContext();

        // GET: Destinations
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Destinations.ToList());
        }

        // GET: Destinations/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            Bus bus = db.Buses.Find(destination.BusId);
            destination.Bus = bus;
            destination.Tickets = db.Tickets.Where(ticket => ticket.DestinationId == destination.DestinationId).ToList<Ticket>();
            if (destination == null)
            {
                return HttpNotFound();
            }
            
            ViewModel des = new ViewModel();
            des.Destinations = destination;
            des.Tickets = destination.Tickets;
            List<SelectListItem> list = new List<SelectListItem>
            {
            new SelectListItem { Text = "--- Select ---", Value = 0.ToString() },
            new SelectListItem { Text = "One Way Price ("+ destination.PriceOneWay.ToString()+")" , Value = destination.PriceOneWay.ToString() },
            new SelectListItem { Text = "Two Way Price ("+ destination.PriceTwoWay.ToString()+")", Value = destination.PriceTwoWay.ToString()},
            new SelectListItem { Text = "Student Price ("+ destination.PriceStudent.ToString()+")", Value = destination.PriceStudent.ToString() },
            };
            ViewBag.ceni = list;
            ViewBag.destination = destination;
            return View(des);
        }

        // GET: Destinations/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (var bus in db.Buses.ToList<Bus>())
            {
                list.Add(new SelectListItem() { Value = bus.BusId.ToString(), Text = bus.Name });
            }
            ViewBag.Busovi = list;
            //ViewBag.Avtobusi = db.Buses.ToList<Bus>();
            return View();
        }

        // POST: Destinations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DestinationId,From,To,PriceOneWay,PriceTwoWay,PriceStudent,BusId")] Destination destination)
        {
            if (ModelState.IsValid)
            {
                db.Destinations.Add(destination);
                //list<bus> buses = db.buses.tolist<bus>();
                //bus bus = buses.find(x => x.busid == destination.busid);
                //for(int i = 0; i < bus.numberofseats; i++)
                //{
                //    ticket ticket = new ticket();
                //    db.tickets.add(ticket);
                //}
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(destination);
        }

        // GET: Destinations/Edit/5
        [Authorize(Roles ="Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            if (destination == null)
            {
                return HttpNotFound();
            }
            return View(destination);
        }

        // POST: Destinations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DestinationId,From,To,PriceOneWay,PriceTwoWay,PriceStudent")] Destination destination)
        {
            if (ModelState.IsValid)
            {
                db.Entry(destination).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(destination);
        }

        // GET: Destinations/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            if (destination == null)
            {
                return HttpNotFound();
            }
            return View(destination);
        }

        // POST: Destinations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Destination destination = db.Destinations.Find(id);
            db.Destinations.Remove(destination);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BusReservation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusReservation.Models;

namespace BusReservation.Controllers
{
    public class HomeController : Controller
    {
        private BusReservationContext db = new BusReservationContext();
        public ActionResult Index()
        {
            ViewBag.popularniDestinacii = db.Destinations.ToList().Take(6);
            return View(db.Buses.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BusReservation/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BusReservation/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BusReservation/Views/Home/Index.cshtml
@model IEnumerable<BusReservation.Models.Bus>

@{
    ViewBag.Title = "Home Page";
}
<div class="row">
    <div class="col-md-9">
        <div class="jumbotron">
            <h1>Register and get 25% off</h1>
            <p class="lead">Register and get your first ticket for 25% off the price. Get fast and secure everywhere with our transportation.</p>
            @if (User.Identity.IsAuthenticated)
            {
                <p><a href="http://localhost:50811/Destinations/Index" class="btn btn-primary btn-lg">Buy tickets now &raquo;</a></p>
            }
            @if (User.Identity.IsAuthenticated == false)
            {
                <p><a href="http://localhost:50811/Account/Register" class="btn btn-primary btn-lg">Register now &raquo;</a></p>
            }

        </div>
    </div>
    @{ 
        var list = ViewBag.popularniDestinacii as IEnumerable<BusReservation.Models.Destination>;
    }
    <div class="col-md-3">
            <h2>Popular Destinations</h2>
            <ul class="list-group">
                @foreach (var i in list)
                {
                <li class="list-group-item">@i.From - @i.To <span style="float:right">@Html.ActionLink("see more", "Details", "Destinations", new { id = i.DestinationId }, new { })</span></li>
                }
            </ul>
        </div>
</div>

<hr />

<h3 style="margin-bottom:0px">Bus Transporters</h3>
<hr style="margin-top:10px" />
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <div class="jumbotron" style="padding:20px">
                <h3>@item.Name</h3>
                <img src="~/Content/Images/@(item.BusId).jpg" alt="vardar-express" class="img-circle" style="display:block; margin:auto; width:150px; height:150px" />
                <br />
                <p style="font-size:14px">@Html.ActionLink("See more information for " + item.Name, "Details", "Buses", new { id = item.BusId }, new { })</p>
            </div>
        </div>
    }
</div>


<style>
    .box {
        padding: 60px 0px;
    }

    .box-part {
        background: #FFF;
        border-radius: 0;
        padding: 60px 10px;
        margin: 30px 0px;
    }

    .text {
        margin: 20px 0px;
    }

    .fa {
        color: #4183D7;
    }
</style>